export const FORM_IDS = {
    PURCHASE_REQUEST: 1,
    REQUEST_FOR_QUOTATION: 2,
    PURCHASE_ORDER: 3,
    VENDOR_COMPANIES: 4,
    PROCUREMENT_USERS: 6,
    ENTITIES: 7,
    GLOBAL_CONFIGURATION: 8,
    LOGS: 9,
    ACL: 10,
    WORKFLOW_SETUP: 11,
    VENDOR_ONBOARDING: 12,
    INVITATION: 13,
    EMAIL_TEMPLATE_LIST: 14,
    BULK_COMPANY_ONBOARDING: 15,
    INVENTORY_TRANSFER: 16
} as const;
